# Generated by Django 4.0.1 on 2023-08-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('spent_money', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListNameStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_csv.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_csv.listnamestone')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='gems',
            field=models.ManyToManyField(to='app_csv.ListNameStone'),
        ),
    ]
