# Generated by Django 4.0.1 on 2023-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='spent_money',
            field=models.IntegerField(default=0),
        ),
    ]
